### PR TITLE
add GitHub Actions

### PR DESCRIPTION
**Pull request by mathiask88**

### CODE REVIEW

**Comment by mathiask88** [comment]
@Apollon77 I tried to be as minimalist as possible. Do you miss any functionality from your PR?

**Comment by Apollon77** [comment]
In a first mobile device view looks good. Go ahead

**Comment by Apollon77** [comment]
PS: the question is if it not makes sense to add node-gyp as dep to make sure it also works for users with nodes 12/14/16 that most likel never get a new bpm version but python 3.12 will go out next year.

**Comment by mathiask88** [comment]
Python version is just for latest macos. They dropped support of disutils in python 3.12. prebuild bundles it's own node-gyp. I would keep this workaround until prebuild upgrades to node-gyp 10 that solves the issue. Instead of forcing python 3.11 I could also install disutils via pip in de CI. Node 12/14/16 should build fine. But they are out of maintenance, so good if it works, but won't put too much effort to get these old versions working.

**Comment by Apollon77** [comment]
Sure ... yes with prebuild ideally the issue is also "solved" for the users ... yes

**Comment by Apollon77** [comment]
@mathiask88 Please check ... 1.0.7 is not available on npm!

**Comment by mathiask88** [comment]
I know, still fighting with the CI and old node versions. Will apply a patch this evening or latest on Saturday. And then release the new version to npm.

**Comment by mathiask88** [comment]
released on npm.. Sorry I had to deal with the npm/Github service this week (which was very nice and helpful btw) because I never setup 2FA and my account got locked 😅

**Comment by Apollon77** [comment]
Thank you very much!

**Pull request merged**
