### PR TITLE
Node.js 20 compatibility

### PR DESCRIPTION
**Pull request by Apollon77**
This PR is upgrading dependencies and also adds GitHub actions businging. I found out that Node.js 4 and 6 would no longer install so I removed it also frpm the package.json.

Please release a version to make the great library compatible with Node.js 20 too.

because I tried several things maybe better to squash&merge :-)

### CODE REVIEW

**Comment by mathiask88** [comment]
I'll have a look in the next days. I also had some github actions changes locally. Hope a fix till end of the week works for you :)

**Comment by Apollon77** [comment]
Awesome thank you!

**Comment by Apollon77** [comment]
PS: If you like just remove my GHA ... it was mainly also for me to proof the "dep increase is enough" solution as working. So also ok for me if you take relevant changes and do not merge.

**Comment by mathiask88** [comment]
see #94

**Pull request closed without merging**
