### PR TITLE
Updated Readme, changed PduLength to PDULength

### PR DESCRIPTION
**Pull request by DJWassink**
Just a small update to the readme PduLength seems to be PDULength

### CODE REVIEW

**Comment by mathiask88** [comment]
Yes, you are right. Can you also change `PduRequested` to `PDURequested` and force push?

**Comment by DJWassink** [comment]
Aah right completely missed the `PDURequested`, added it

**Comment by mathiask88** [comment]
Would be cool if you can sqash the two commits into one and give it a proper commit message.

**Comment by DJWassink** [comment]
Hope this is acceptable ;) thanks for your awesome work so far on this wrapper!

**Comment by mathiask88** [comment]
Thank you very much for contributing! I'm very pleased to hear that and I hope the few guys using it are creating awesome stuff with it ;)

**Pull request merged**
